package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "profiler_proto_library",
    deps = [
        ":profiler_proto",
    ],
)

proto_library(
    name = "profiler_proto",
    srcs = [
        "profiler_info.proto",
    ],
)
